### ISSUE TITLE
what resources did you refer to?

### ISSUE THREAD

**Issue by nyck33** [jiankang1991/tiny_proj_PID_para_twiddle_bayesian_opti#1]
Hi Jiankang,

  This is very impressive, what resources did you refer to regarding Bayesian optimization?

**Comment by jiankang1991** [comment]
@nyck33  Hi, I use the python package hyperopt, you can have a look at:
https://towardsdatascience.com/an-introductory-example-of-bayesian-optimization-in-python-with-hyperopt-aae40fff4ff0

**Comment by nyck33** [comment]
@jiankang1991 thanks man!
